### ISSUE TITLE
add site to distribution management

### ISSUE THREAD

**Issue by lithium147** [arey/maven-config-github-cloudbees#2]
For completeness, you could add a site element to the distributionManagement.

I found an example here:
https://repository-dynacrongroup.forge.cloudbees.com/release/sites/webtest-quickstart/distribution-management.html

Look likes it just put things in a "sites" dir under the cloudbees-forge release repo.

**Comment by arey** [comment]
Thanks lithium147. I have updated the pom.xml. It's maven site is now available on cloudbees: https://repository-javaetmoi.forge.cloudbees.com/release/sites/maven-config-github-cloudbees/index.html
